"""
* 외부변수 설정
"""
SCREEN_WIDTH = 480
SCREEN_HEIGHT = 640
WINDOW_TITLE = "BOUNCE BALL ({}x{})".format(SCREEN_WIDTH, SCREEN_HEIGHT)

PAD_WIDTH = 100
PAD_HEIGHT = 10
PAD_COLOR = "blue"
PAD_SPEED = 3

BALL_DIA = 15
BALL_COLOR = "red"
BALL_SPEED = 3
